services:
  - type: worker
    name: telegram-bot
    runtime: python
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: TOKEN
        value: "8021635930:AAHIJCh1_eXsTx2QueVwlLk0puF8JrXH5mI"
